[package]
name = "child-processes"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.5", features = ["tokio"] }
iced_native = "0.6"
tokio = { version = "1.21.2", features = ["process", "sync", "io-util"] }
