[package]
name = "child-processes"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.8", features = ["tokio"] }
tokio = { version = "1.21.2", features = ["process", "sync", "io-util"] }
