[package]
name = "hover-component"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", branch = "advanced-text", features = [ "advanced", "lazy" ] }
